CREATE TABLE PRODUTO(
	ID				UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	PRECO			DECIMAL(18,2)		NOT NULL,
	QUANTIDADE		INTEGER				NOT NULL,
	DATAVALIDADE	DATETIME			NOT NULL,
	DESCRICAO		NVARCHAR(500)		NOT NULL,
	ATIVO			INTEGER				NOT NULL DEFAULT(1),
	DATAINCLUSAO	DATETIME			NOT NULL,
	DATAALTERACAO	DATETIME			NOT NULL,
	PRIMARY KEY(ID))
	GO