--CRIANDO A TABELA DE USUARIO
CREATE TABLE USUARIO(
	ID				UNIQUEIDENTIFIER		NOT NULL,
	NOME			NVARCHAR(150)			NOT NULL,
	EMAIL			NVARCHAR(150)			NOT NULL UNIQUE,
	SENHA			NVARCHAR(50)			NOT NULL,
	DATAINCLUSAO	DATETIME				NOT NULL,
	PRIMARY KEY(ID))
GO

--MODIFICANDO A TABELA DE PRODUTO
--PARA ADICIONAR O CAMPO 'IDUSUARIO'
ALTER TABLE PRODUTO ADD
IDUSUARIO UNIQUEIDENTIFIER
GO

--MODIFICANDO A TABELA DE PRODUTO
--PARA DEFINIR O CAMPO 'IDUSUARIO' COMO CHAVE ESTRANGEIRA
ALTER TABLE PRODUTO ADD CONSTRAINT FK_USUARIO
FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(ID)
GO